Typo in git-commit at git-branch description
github/training-kit pull request #813
Opened 2021-02-12 02:37 UTC by huecester

## Overview
Changed `[banch-name]` to `[branch-name]` under Related Terms

2021-02-12 10:03 UTC, brianamarie commented
Thank you for this fix, @huecester!

2021-02-12 10:03 UTC, merged

2021-02-15 13:11 UTC, kkash18 approved these changes
OpenShift Container

2021-02-15 13:14 UTC, kkash18 requested changes

2021-02-15 13:14 UTC, kkash18 commented on git-guides/git-clone.md
> -- `git branch`: This shows the existing branches in your local repository. You can also use `git branch [banch-name]` to create a branch from your current location, or `git branch --all` to see all b
``

2021-02-15 13:14 UTC, kkash18 commented on git-guides/git-clone.md
> +- `git branch`: This shows the existing branches in your local repository. You can also use `git branch [branch-name]` to create a branch from your current location, or `git branch --all` to see all
[]()

2021-02-15 13:14 UTC, kkash18 commented on git-guides/git-clone.md
> -- `git branch`: This shows the existing branches in your local repository. You can also use `git branch [banch-name]` to create a branch from your current location, or `git branch --all` to see all b
git-guides/git-clone.md@github-cla

2021-02-15 13:15 UTC, kkash18 approved these changes